name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install credentials
      run: |
        mkdir -p lib/.secret 
        echo $CONTENT > lib/.secret/credentials.json
      shell: bash
      env:
        CONTENT: ${{ secrets.GOOGLE_CREDENTIAL_CONTENT }}
    - name: Install build dependencies
      uses: docker://amaysim/serverless:1.53.0
      with:
        args: yarn install
    - name: Install lib dependencies
      uses: docker://amaysim/serverless:1.53.0
      with:
        args: yarn --cwd lib install
    - name: Deploy prod platform
      uses: docker://amaysim/serverless:1.53.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: yarn --cwd lib deploy:prod
