name: PR CI

on:
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing for now
        run: echo Nothing to do
        shell: bash
    # - uses: actions/checkout@v1
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: '13.x'
    # - name: Install build dependencies
    #   run: yarn install
    # - name: Install lib dependencies
    #   run: yarn install --cwd lib
    # - name: Run unit tests
    #   run: yarn test:unit
    #   env:
    #     STAGE: dev

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup NodeJS
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '16.x'
        cache: 'yarn'
    - name: Setup JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '19'
        distribution: 'zulu'
    - name: Install build dependencies
      run: yarn install
    - name: Install lib dependencies
      run: yarn --cwd lib install
    - name: Build project
      run: yarn shadow release api
    - name: Deploy test platform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FAUNADB_TOKEN: ${{ secrets.FAUNADB_TOKEN }}
        NEWRELIC_ACCOUNTID: ${{ secrets.NEWRELIC_ACCOUNTID }}
        NEWRELIC_ACCOUNTKEY: ${{ secrets.NEWRELIC_ACCOUNTKEY }}
      run: yarn --cwd lib deploy:test
    - name: Run intergration tests
      run: yarn test:integration
      env:
        STAGE: test
