name: PR CI

on:
  pull_request:
    branches: 
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing for now
        run: echo Nothing to do
        shell: bash
    # - uses: actions/checkout@v1
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: '13.x'
    # - name: Install build dependencies
    #   run: yarn install
    # - name: Install lib dependencies
    #   run: yarn install --cwd lib
    # - name: Run unit tests
    #   run: yarn test:unit
    #   env:
    #     STAGE: dev

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install credentials
      run: |
        mkdir -p lib/.secret 
        echo $CONTENT > lib/.secret/credentials.json
      shell: bash
      env:
        CONTENT: ${{ secrets.GOOGLE_CREDENTIAL_CONTENT }}
    - name: Install build dependencies
      uses: docker://amaysim/serverless:1.53.0
      with:
        args: yarn install
    - name: Install lib dependencies
      uses: docker://amaysim/serverless:1.53.0
      with:
        args: yarn --cwd lib install
    - name: Build project
      uses: docker://amaysim/serverless:1.53.0
      with:
        args: yarn shadow release api
    - name: Deploy test platform
      uses: docker://amaysim/serverless:1.53.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: yarn --cwd lib deploy:test
    - name: Run intergration tests
      uses: docker://amaysim/serverless:1.53.0
      env:
        STAGE: test
      with:
        args: yarn test:integration
