name: PR CI

on:
  pull_request:
    branches:
      - master

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'
        cache: 'yarn'
    - name: Setup JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Install build dependencies
      run: yarn install
    - name: Install lib dependencies
      run: yarn --cwd lib install
    - name: Build project
      run: yarn shadow release api
    - name: Deploy test platform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FAUNADB_TOKEN: ${{ secrets.FAUNADB_TOKEN }}
        NEWRELIC_ACCOUNTID: ${{ secrets.NEWRELIC_ACCOUNTID }}
        NEWRELIC_ACCOUNTKEY: ${{ secrets.NEWRELIC_ACCOUNTKEY }}
      run: yarn --cwd lib deploy:test
