name: PR CI

on:
  pull_request:
    branches: 
      - master

jobs:
  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Install dependencies
  #     uses: docker://amaysim/serverless:1.53.0
  #     with:
  #       args: yarn install
  #   - name: Run unit tests
  #     uses: docker://amaysim/serverless:1.53.0
  #     with:
  #       args: yarn test:unit

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - name: Install dependencies
    #   uses: docker://amaysim/serverless:1.53.0
    #   with:
    #     args: yarn install
    - name: Install credentials
      run: |
        echo $CONTENT > .secret/credentials.json
        ls .
      shell: bash
      env:
        CONTENT: ${{ secrets.GOOGLE_CREDENTIAL_CONTENT }}
    # - name: Deploy test platform
    #   uses: docker://amaysim/serverless:1.53.0
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   with:
    #     args: yarn deploy:test
    # - name: Run intergration tests
    #   uses: docker://amaysim/serverless:1.53.0
    #   env:
    #     STAGE: test
    #   with:
    #     args: yarn test:integration
